Hw2
Alexandr-Kokorin/JavaCourse2023 pull request #3
Opened 2023-10-20 08:05 UTC by Alexandr-Kokorin

2023-10-20 23:32 UTC, kkmikhaylova requested changes

2023-10-20 23:32 UTC, kkmikhaylova commented on src/main/java/edu/hw2/task1/Main.java
> +        var two = new Expr.Constant(2);
Хотелось бы видеть это в тестах)

2023-10-20 23:32 UTC, kkmikhaylova commented on src/main/java/edu/hw2/task2/Square.java
> +public class Square extends Rectangle {
При такой реализации у нас вполне может быть объект Квадрат с разными сторонами, это нарушение контракта. Обрати внимание на подсказку 1

2023-10-20 23:32 UTC, kkmikhaylova commented on src/main/java/edu/hw2/task3/PopularCommandExecutor.java
> +            for (int i = 0; i < maxAttempts; i++) {
Если tryExecute не смог выполнить команду (превышено количество попыток), то нужно вернуть ConnectionException, при этом сохранив оригинальное исключение в параметре cause

2023-10-20 23:32 UTC, kkmikhaylova commented on src/test/java/edu/hw2/Task4Test.java
> +        assertThat(callingInfo1).isEqualTo(callingInfo2);
А как мы поймём, что мы сломали логику работы метода? Мы 2 раза вызвали один метод без параметров, логично, что результаты аналогичны. Давай перепишем на проверку конкретного значения внутри `callingInfo1`

2023-10-20 23:32 UTC, kkmikhaylova commented on src/test/java/edu/hw2/Task3Test.java
> +public class Task3Test {
Подумай какие ещё тесты тут можно написать

2023-10-21 19:53 UTC, Alexandr-Kokorin commented
Вроде бы всё исправил)

2023-10-22 19:53 UTC, kkmikhaylova approved these changes

2023-10-22 19:53 UTC, kkmikhaylova commented on src/main/java/edu/hw2/task2/Rectangle.java
> +        return new Rectangle(width, height);
Давай на будущее договоримся переносить тесты из заданий как есть, тут из-за отсутствия методов setWidth/setHeight тест всё-таки не аналогичен) Вижу, что суть понял, поэтому задание засчитываю 👍

2023-10-23 09:49 UTC, merged